# Preparing the data for analysis

### Imported the parquet file because its the suitable choice to save the columns with the real data types

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_parquet('../Cleaned_data/Superstore_cleaned.parquet')
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

## Creating new columns to answer the KPI questions
#### business questions:
1. How is the business doing overall?
   KPIs: Total Sales, Total Profit, Profit Margin %, Total Orders,
   Total Customers, Average Order Value

2. Is the business growing?
   KPIs: Sales and Profit by year, Year-over-Year growth %

3. Are there seasonal patterns?
   KPI: Sales by month (busy and slow periods)

4. Which categories and sub-categories bring the most sales and profit?
   KPIs: Sales, Profit, and Profit Margin % by Category and Sub-Category

5. Which sub-categories lose money?
   KPI: Sub-categories with negative total profit

6. Do discounts hurt profit?
   KPI: Profit Margin % by discount level (None, Standard, Medium, High)

7. Which regions and states perform best and worst?
   KPIs: Sales, Profit, and Profit Margin % by Region and State

8. Which customer segments are the most valuable, and how fast do we deliver?
   KPIs: Sales, Profit, and Average Order Value by Segment;
   Average Delivery Days by Ship Mode

In [3]:
df.dtypes

Order ID                 object
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code              object
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [4]:
df['Year'] = df['Order Date'].dt.year  # for question number 2
df['Month'] = df['Order Date'].dt.month   # for question number 3
df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df.isna().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Year             0
Month            0
Delivery Days    0
dtype: int64

In [5]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Delivery Days
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,2016,11,3
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,2016,11,3
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,2016,6,4
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,2015,10,7
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,2015,10,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,...,Furniture,Furnishings,Ultra Door Pull Handle,25.25,3,0.20,4.10,2014,1,2
9989,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,15.63,2017,2,5
9990,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,Technology,Phones,Aastra 57i VoIP phone,258.58,2,0.20,19.39,2017,2,5
9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.00,13.32,2017,2,5
9992,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.95,2017,5,5

## Prepare Stage: New Columns

The questions need information that is not directly in the data, so I created these columns from existing ones. The cleaned data was loaded from the Parquet file, which keeps the column types (dates stay dates and Postal Code stays text). The CSV version does not store types, so anyone reading it must specify the dates and Postal Code when loading.

| New column | How it is built | Question it serves | Check | Result |
|---|---|---|---|---|
| Year | Year taken from Order Date | Q2: Is the business growing? | Unique values should be exactly 2014, 2015, 2016, 2017 | Only 2014, 2015, 2016 and 2017 present. Passed. |
| Month | Month number (1 to 12) taken from Order Date | Q3: Are there seasonal patterns? | Unique values should be exactly 1 to 12 | Values 1 to 12 only. Passed. |
| Delivery Days | Ship Date minus Order Date, converted to a whole number of days | Q8: How fast do we deliver? | Minimum should be 0 or higher, maximum should be a small number, and Same Day should average close to 0 | Minimum 0, maximum 7 days. Averages: Same Day 0.044 , First Class 2.183 , Second Class 3.238 , Standard Class 5.007. Passed. |
| Discount Level | Discount grouped into four levels: None (0%), Standard (above 0% up to 20%), Medium (above 20% up to 40%), High (above 40%) | Q6: Do discounts hurt profit? | Every row has a level (no empty values), and the counts per level add up to 9,993 | No empty values. Counts: None 4,798, Standard 3,803, Medium 459, High 933. Passed. |

### Notes on the columns

- Month is only the month number, without the year. It adds up all Januaries across the years, which is what the seasonality question needs. A monthly timeline will be built in Power BI from Order Date.
- Subtracting two dates gives a time difference, not a number, so `.dt.days` is used to get plain integers.
- Discount is stored as a fraction (0.2 means 20%).

### Discount Level: why these boundaries

- None is its own level because it is the baseline, with 48% of the rows (4,798).
- Standard covers 10%, 15% and 20% discounts. Most of its rows are exactly 20% (3,657 of 3,803), which is the usual promotion in this store, so I named it Standard and not Low.
- The boundaries at 20% and 40% were chosen after looking at the value counts of Discount, and before looking at profit, so the groups are not shaped to fit the answer.
- A value equal to a boundary goes into the lower group (0.20 is Standard, 0.40 is Medium).
- Expected row counts: None 4,798, Standard 3,803, Medium 459, High 933. The smallest level has 459 rows, which is enough for a reliable margin.

### Checks

- No missing values in the new columns:0 missing values in all four new columns.
- Final shape:9,993 rows and 24 columns.

In [6]:
display(sorted(df['Year'].unique()))
print(30*'*')
display(sorted(df['Month'].unique()))
print(30*'*')
display(df['Delivery Days'].min(), df['Delivery Days'].max())
display(df.groupby('Ship Mode')['Delivery Days'].mean())

[2014, 2015, 2016, 2017]

******************************

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

******************************

0

7

Ship Mode
First Class       2.182705
Same Day          0.044199
Second Class      3.238046
Standard Class    5.006704
Name: Delivery Days, dtype: float64

In [7]:
df['Discount'].value_counts().sort_index()

Discount
0.00    4798
0.10      94
0.15      52
0.20    3657
0.30     226
0.32      27
0.40     206
0.45      11
0.50      66
0.60     138
0.70     418
0.80     300
Name: count, dtype: int64

In [8]:
df['Discount Level'] = pd.cut(
    df['Discount'],
    bins=[-0.01, 0, 0.2, 0.4, 1],
    labels=['None', 'Standard', 'Medium', 'High']
)
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Delivery Days,Discount Level
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,2016,11,3,None
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,2016,11,3,None
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,2016,6,4,None
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,2015,10,7,High
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,2015,10,7,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,...,Furnishings,Ultra Door Pull Handle,25.25,3,0.20,4.10,2014,1,2,Standard
9989,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,15.63,2017,2,5,None
9990,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,Phones,Aastra 57i VoIP phone,258.58,2,0.20,19.39,2017,2,5,Standard
9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.00,13.32,2017,2,5,None
9992,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,...,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.95,2017,5,5,None

In [ ]:
print(df['Discount Level'].value_counts())

0
Discount Level
None        4798
Standard    3803
High         933
Medium       459
Name: count, dtype: int64

In [10]:
df[['Year', 'Month', 'Delivery Days', 'Discount Level']].isna().sum()

Year              0
Month             0
Delivery Days     0
Discount Level    0
dtype: int64

In [11]:
df.shape

(9993, 24)

In [12]:
df.to_csv('../Processed_data/Superstore_Processed.csv' , index=False)
df.to_parquet('../Processed_data/Superstore_Processed.parquet' , index=False)